"""Build a nine-model LaTeX appendix table of bootstrap mediation results.

CPU-only. Loads no model and runs no forward pass; every number here is read
from ``results/logs/hiring_mediation_<label>.json``, which was produced by
``src/hiring_disparity.py::bootstrap_mediation`` for all nine models (the
original four-model manuscript subset plus five newer checkpoints added
later). No mediation bootstrap is re-run here.

Output (booktabs style, ``\\input``-able from the manuscript)
---------------------------------------------------------------
results/tables/mediation_9model.tex
    Appendix table: for each of the nine models, four rows
    (race x warmth, race x competence, gender x warmth, gender x competence)
    giving the standardized path coefficients a, b, the bootstrap indirect
    effect a*b with its 95% CI, and a significance marker.

Usage
-----
    python -m src.build_paper_mediation_table --config config/config.yaml
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

from src.utils.config import load_config

# Same canonical order/display names as src/build_paper_probe_tables.py, so
# this table lists models in the same order as Table 1 (tab:probe_human) and
# the appendix disparity tables.
MODEL_ORDER = (
    "gemma3_12b",
    "gemma3_27b",
    "llama31_8b",
    "gemma4_12b",
    "gemma4_26b_a4b",
    "gemma4_31b",
    "qwen3_14b",
    "qwen36_27b",
    "qwen36_35b_a3b",
)

DISPLAY_NAME = {
    "gemma3_12b": "Gemma-3-12B",
    "gemma3_27b": "Gemma-3-27B",
    "llama31_8b": "Llama-3.1-8B",
    "gemma4_12b": "Gemma-4-12B",
    "gemma4_26b_a4b": "Gemma-4-26B-A4B",
    "gemma4_31b": "Gemma-4-31B",
    "qwen3_14b": "Qwen3-14B",
    "qwen36_27b": "Qwen3.6-27B",
    "qwen36_35b_a3b": "Qwen3.6-35B-A3B",
}

# Row order within each model block: (grouping key in JSON, probe key in JSON).
ROW_ORDER = (
    ("race(Black=1)", "warmth"),
    ("race(Black=1)", "competence"),
    ("gender(Female=1)", "warmth"),
    ("gender(Female=1)", "competence"),
)


def fmt_ie(entry: dict) -> tuple[str, str]:
    """Return (IE cell, 95% CI cell) as two separate tabular columns."""
    ie = entry["indirect_effect"]
    lo = entry["ci_95_lo"]
    hi = entry["ci_95_hi"]
    marker = r"$^{\dagger}$" if entry["significant_95"] else ""
    sign = "+" if ie >= 0 else ""
    return f"{sign}{ie:.3f}{marker}", f"[{lo:+.3f}, {hi:+.3f}]"


def build_table(log_dir: Path, out_path: Path) -> None:
    seeds = set()
    n_boots = set()
    per_model: dict[str, dict] = {}
    for label in MODEL_ORDER:
        log_path = log_dir / f"hiring_mediation_{label}.json"
        payload = json.loads(log_path.read_text(encoding="utf-8"))
        seeds.add(payload["seed"])
        n_boots.add(payload["n_boot"])
        by_key = {(m["grouping"], m["probe"]): m for m in payload["mediation"]}
        per_model[label] = {
            "n_matched": payload["n_matched"],
            "n_race_subset": payload["n_race_subset"],
            "rows": by_key,
        }

    if len(seeds) != 1 or len(n_boots) != 1:
        raise RuntimeError(
            f"Expected one shared seed/n_boot across all nine models, "
            f"got seeds={seeds} n_boots={n_boots}"
        )
    seed = seeds.pop()
    n_boot = n_boots.pop()

    n_matched_vals = {per_model[l]["n_matched"] for l in MODEL_ORDER}
    n_race_vals = {per_model[l]["n_race_subset"] for l in MODEL_ORDER}
    n_matched = n_matched_vals.pop() if len(n_matched_vals) == 1 else None
    n_race = n_race_vals.pop() if len(n_race_vals) == 1 else None

    n_sig = sum(
        1
        for label in MODEL_ORDER
        for key in ROW_ORDER
        if per_model[label]["rows"][key]["significant_95"]
    )
    n_total = len(MODEL_ORDER) * len(ROW_ORDER)

    grouping_label = {"race(Black=1)": "Race (Black=1)", "gender(Female=1)": "Gender (Female=1)"}
    probe_label = {"warmth": "Warmth", "competence": "Competence"}

    lines = [
        "% Generated by src/build_paper_mediation_table.py.",
        "% Source: results/logs/hiring_mediation_<label>.json for all nine models "
        "(src/hiring_disparity.py::bootstrap_mediation; CPU-only, no re-run here).",
        r"\begin{table}[htbp]",
        r"\centering",
        r"\caption{\textbf{Bootstrap mediation of name-group callback disparities "
        r"through warmth and competence probe scores, all nine models.} "
        r"Path: name group $\to$ probe score $\to$ callback margin, standardized "
        f"coefficients, Baron--Kenny/Preacher--Hayes bootstrap ({n_boot:,} resamples, "
        f"seed {seed}"
        + (f", $n={n_matched}$, race subset $n={n_race}$" if n_matched and n_race else "")
        + r"). "
        r"$a$ is the coefficient of group on probe score; $b$ is the coefficient of "
        r"probe score on callback margin, controlling for group; IE $= a \times b$ is "
        r"the indirect (mediated) effect. "
        r"$^{\dagger}$ marks a 95\% bootstrap CI that excludes zero. "
        f"{n_sig} of {n_total} tests are significant at this uncorrected threshold; "
        r"only the Llama-3.1-8B race--warmth path (main text) survives a "
        f"Bonferroni correction across all {n_total} tests "
        r"($\alpha = 0.05/" + str(n_total) + r"$), so the remaining paths listed here, "
        r"including all newer-model paths, should be read as suggestive rather than "
        r"confirmed.}",
        r"\label{tab:mediation_9model}",
        r"\scriptsize",
        r"\setlength{\tabcolsep}{4pt}",
        r"\begin{tabular}{@{}lllrrrl@{}}",
        r"\toprule",
        r"Model & Grouping & Probe & $a$ & $b$ & IE & 95\% CI \\",
        r"\midrule",
    ]
    for label in MODEL_ORDER:
        rows = per_model[label]["rows"]
        for i, key in enumerate(ROW_ORDER):
            entry = rows[key]
            model_cell = DISPLAY_NAME[label] if i == 0 else ""
            grouping, probe = key
            ie_cell, ci_cell = fmt_ie(entry)
            lines.append(
                f"{model_cell} & {grouping_label[grouping]} & {probe_label[probe]} & "
                f"{entry['a']:+.3f} & {entry['b']:+.3f} & {ie_cell} & {ci_cell} \\\\"
            )
        lines.append(r"\addlinespace")
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"[mediation_table] wrote {out_path} ({len(MODEL_ORDER)} models, "
          f"{n_total} rows, {n_sig} significant, seed={seed}, n_boot={n_boot})")


def main() -> None:
    args = parse_args()
    cfg = load_config(args.config)
    log_dir = Path(cfg.paths.logs)
    table_dir = Path(cfg.paths.results) / "tables"
    build_table(log_dir, table_dir / "mediation_9model.tex")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", default="config/config.yaml")
    return parser.parse_args()


if __name__ == "__main__":
    main()
